apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels: 
    app: wordpress
spec: 
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata: 
      labels:
        app: wordpress
        uses: mysql
        name: wordpress
    spec:
      containers: 
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              # change this - must match mysql.yaml password
              value: password
          ports: 
            - containerPort: 80
              name: wordpress
          volumeMounts:
              # name must match the volume name below
            - name: wordpress-storage
              # mount path within the container
              mountPath: /var/www/html
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi  
      volumes:
        - name: wordpress-storage
          emptyDir: {}
